client_id: <%= ENV["154813271628-m63oii8ou92874djpibkosj54ub4bono.apps.googleusercontent.com"] %>
client_secret: <%= ENV["mOfV5821kUY1jcRSEE22ysEU"] %>
access_token: <%= ENV["ya29.GlutA7bKMLwkHs6rXFYU92vZGy7wZX2CsGpjDhukPYqUyE0BhzeiEFtUojGflUj8-gBDhWKdxlrpzaIi7zbE91WBQldvqfcw9B-SpRQwdQTLqnb_1LA7dt1Y3Te9"] %>
refresh_token: <%= ENV["1/rAuECXRzCoPkqVOGVb0-GgkmuSCF5nz-nsw4265ZWLY"] %>